
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MENOS = 7;
  public static final int MENOR = 11;
  public static final int ELSE = 4;
  public static final int IGUAL = 13;
  public static final int THEN = 3;
  public static final int IF = 2;
  public static final int ID = 18;
  public static final int PONTOVIRG = 15;
  public static final int NUM = 19;
  public static final int MAIS = 6;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int VIRG = 14;
  public static final int DEF = 5;
  public static final int DIVISAO = 9;
  public static final int error = 1;
  public static final int MAIOR = 12;
  public static final int APARENT = 16;
  public static final int ATR = 10;
  public static final int FPARENT = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "DEF",
  "MAIS",
  "MENOS",
  "MULT",
  "DIVISAO",
  "ATR",
  "MENOR",
  "MAIOR",
  "IGUAL",
  "VIRG",
  "PONTOVIRG",
  "APARENT",
  "FPARENT",
  "ID",
  "NUM"
  };
}

